name: Viral URL Rotate

on:
  workflow_dispatch:      # Enables the Run workflow button
  push:                   # Runs when you edit files
    branches: [ main ]
  schedule:
    - cron: "30 18 * * *"   # Runs daily at 18:30 UTC (00:00 in Sri Lanka)

jobs:
  rotate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update redirect target
        run: |
          DATE=$(date -u +"%Y-%m-%d")
          echo "https://todaylankaviralnews.github.io/viral/$DATE/" > redirect_target.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add redirect_target.txt
          git commit -m "Update redirect URL for $DATE"
          git push
